max_length: 256

languages: 
  - af
  - ar
  - bg
  - bn
  - bs
  - ca
  - cs
  - da
  - de
  - el
  - en
  - eo
  - es
  - et
  - eu
  - fi
  - fr
  - gl
  - he
  - hi
  - hr
  - hu
  - id
  - is
  - it
  - ja
  - ka
  - ko
  - lt
  - lv
  - mk
  - ml
  - ms
  - nl
  - 'no'
  - pl
  - pt
  - ro
  - ru
  - si
  - sk
  - sl
  - sq
  - sv
  - th
  - tr
  - uk
  - vi
  - zh
